output "project_id" {
  description = "Railway project UUID."
  value       = railway_project.hela.id
}

output "default_environment_id" {
  description = "Railway environment id for the project's default (production) environment."
  value       = local.env_id
}

output "service_ids" {
  description = "Railway service UUIDs by name. Useful for `railway variable set --service <id>`."
  value = {
    postgres = railway_service.postgres.id
    gateway  = railway_service.gateway.id
    control  = railway_service.control.id
    web      = railway_service.web.id
    app      = railway_service.app.id
  }
}

output "urls" {
  description = "Public URLs for every deployed service."
  value = {
    web     = "https://${local.web_domain}"
    app     = "https://${local.app_domain}"
    gateway = "https://${local.gateway_domain}"
    control = "https://${local.control_domain}"
  }
}

output "internal_dns" {
  description = "Internal Railway DNS (used by services to reach each other)."
  value = {
    gateway  = "${railway_service.gateway.name}.railway.internal"
    control  = "${railway_service.control.name}.railway.internal"
    postgres = "${railway_service.postgres.name}.railway.internal"
  }
}

# --- generated secrets, for the operator to feed into railway CLI -------
#
# These are sensitive; `terraform output` redacts them. Use
# `terraform output -json | jq -r '.<name>.value'` to extract.

output "generated_secrets" {
  description = "Random secrets generated by Terraform. Pipe into `railway variable set` per env."
  sensitive   = true
  value = {
    postgres_password       = random_password.postgres_password.result
    control_secret_key_base = random_password.control_secret_key_base.result
    gateway_secret_key_base = random_password.gateway_secret_key_base.result
    playground_secret       = random_password.playground_secret.result
    internal_secret         = random_password.internal_secret.result
  }
}

output "next_steps" {
  description = "What to do after `terraform apply`."
  value       = <<-EOT

    Terraform has provisioned the project structure. Variable values
    are NOT managed here — seed each environment via railway CLI:

      bash infra/railway/seed.sh production   # production env
      bash infra/railway/seed.sh dev          # dev (sandbox) env

    The script reads from `terraform output -json` and falls back to
    prompting for the polar/* values it can't generate. See
    `infra/railway/README.md` for the full var matrix.

    URLs once vars are set + a deploy completes:
      web     https://${local.web_domain}
      app     https://${local.app_domain}
      gateway https://${local.gateway_domain}
      control https://${local.control_domain}

    Verify production end to end:
      HELA_GATEWAY=https://${local.gateway_domain} \
      HELA_CONTROL=https://${local.control_domain} \
        uv run scripts/e2e.py
  EOT
}

locals {
  web_domain = "${railway_service_domain.web.subdomain}.up.railway.app"
  app_domain = "${railway_service_domain.app.subdomain}.up.railway.app"
}
